In [4]:
import numpy as np #calculo numerico sobre arrays y matrices 

#crear un arreglo unidimencional
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print('\n')
#crear un arreglo bidimencional
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[1 2 3 4 5]


[[1 2 3]
 [4 5 6]]


## Creacion de arreglos

In [5]:
#arreglos con valores inicializados
#arreglo de ceros
zeros = np.zeros((3,4))
print(zeros)
print('\n')
#arreglo de unos
ones = np.ones((2, 3))
print(ones)
print('\n')
#arreglo con valores contrastes
full = np.full((2, 2), 7)
print(full)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]]


[[7 7]
 [7 7]]


In [6]:
#Arreglos con secuencias numericas
#secuencia de numeros
sequence = np.arange(10)
print(sequence)
print('\n')
#secuencia de numeros con un intervalo
interval = np.arange(1, 10, 2)
print(interval)
print('\n')
#secuencia de numeros equidistantes
linspace = np.linspace(0, 1, 5)
print(linspace)

[0 1 2 3 4 5 6 7 8 9]


[1 3 5 7 9]


[0.   0.25 0.5  0.75 1.  ]


## Propiedades de arreglos

In [7]:
#forma y tamaño
#ver forma del arreglo
print(matrix.shape)
print('\n')
#ver numero de elementos
print(matrix.size)
print('\n')
#ver numero de dimenciones
print(matrix.ndim)

(2, 3)


6


2


In [10]:
#tipos de datos
#ver tipo de dato del arreglo
print(matrix.dtype)
print('\n')
#crear un arreglo de enteros
int_array = np.array([1, 2, 3], dtype=int)
print(int_array)
print('\n')
#crear un arreglo de flotantes
float_array = np.array([1.0, 2.0, 3.0], dtype=float)
print(float_array)

int64


[1 2 3]


[1. 2. 3.]


## Indexacion y slicing

In [11]:
#indexacion basica
arr = np.array([1, 2, 3, 4, 5])

#acceder al elemento
print(arr[0])
print('\n')
#mdificar un elemento
arr[0] = 10
print(arr)

1


[10  2  3  4  5]


In [12]:
#Slicing
#subarreglo
print(arr[1:4])
print('\n')
#subarreglo con paso
print(arr[::2])
print('\n')
#subarreglo invertido
print(arr[::-1])

[2 3 4]


[10  3  5]


[ 5  4  3  2 10]


In [13]:
# Indexacion en arreglos multidimencionales
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#acceder a un elemento
print(matrix[1, 2])
print('\n')
#acceder a una fila comoleta
print(matrix[1, :])
print('\n')
#acceder a una columna completa
print(matrix[:, 1])

6


[4 5 6]


[2 5 8]


## Operaciones matematicas

In [14]:
#operaciones elementales
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#suma
print(a + b)
print('\n')
#resta
print(a - b)
print('\n')
#multiplicacion 
print(a * b)
print('\n')
#divicion
print(a / b)

[5 7 9]


[-3 -3 -3]


[ 4 10 18]


[0.25 0.4  0.5 ]


In [15]:
#funciones universales (ufuncs)
#raiz cuadrada
print(np.sqrt(a))
print('\n')
#seno
print(np.sin(a))
print('\n')
#logaritmo natural
print(np.log(a))

[1.         1.41421356 1.73205081]


[0.84147098 0.90929743 0.14112001]


[0.         0.69314718 1.09861229]


## Algebra lineal

In [16]:
#productos de matrices
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

#productos de matrices
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [17]:
#determinante y transpuesta
#determinante de una matriz
print(np.linalg.det(a))
print('\n')
#transpuesta de una matriz
print(a.T)

-2.0000000000000004


[[1 3]
 [2 4]]


## Manipulacion de arreglos

In [18]:
#cambio de forma
arr = np.arange(1, 13)

#cambiar forma de arreglo
reshaped = arr.reshape((3, 4))
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
#concatenacion y divicion
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

#concatenar arreglos
concat = np.concatenate((a, b), axis=0)
print(concat)
print('\n')
#dividir un arreglo
split = np.array_split(concat, 2, axis=0)
print(split)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


## Estadisticas y agregaciones

In [20]:
#funciones basicas
arr = np.array([1, 2, 3, 4, 5])

#suma
print(np.sum(arr))
print('\n')
#promedio
print(np.mean(arr))
print('\n')
#desviacion estandar
print(np.std(arr))

15


3.0


1.4142135623730951


In [21]:
#agregacion en arreglos multidimencionales
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#sumar por filas
print(np.sum(matrix, axis=1))
print('\n')
#suma por columnas
print(np.sum(matrix, axis=0))

[ 6 15 24]


[12 15 18]
